"""change shipment_date to date

Revision ID: 0c7358795b78
Revises: 49476a53992d
Create Date: 2026-09-26 15:46:05.821809

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0c7358795b78'
down_revision: Union[str, Sequence[str], None] = '49476a53992d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    conn = op.get_bind()
    # Batch mode SQLite'ta CAST(x AS DATE) kullanır: '2026-09-25' -> 2026 olur.
    # Değerleri önce saklıyoruz, tablo yeniden kurulduktan sonra geri yazıyoruz.
    rows = conn.execute(sa.text("SELECT id, shipment_date FROM shipments")).fetchall()

    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.alter_column('shipment_date',
               existing_type=sa.VARCHAR(),
               type_=sa.Date(),
               existing_nullable=True)

    for row_id, value in rows:
        conn.execute(
            sa.text("UPDATE shipments SET shipment_date = :value WHERE id = :id"),
            {"value": value, "id": row_id},
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('shipments', schema=None) as batch_op:
        batch_op.alter_column('shipment_date',
               existing_type=sa.Date(),
               type_=sa.VARCHAR(),
               existing_nullable=True)

    # ### end Alembic commands ###
