"""partner_name, expense paid_by and partner_payments

Revision ID: 0ec34a8480ff
Revises: a934cb1ac28a
Create Date: 2026-09-28 21:35:20.693316

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0ec34a8480ff'
down_revision: Union[str, Sequence[str], None] = 'a934cb1ac28a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('partner_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('vehicle_id', sa.Integer(), nullable=False),
    sa.Column('payment_date', sa.Date(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('notes', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['vehicle_id'], ['vehicles.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('partner_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_partner_payments_id'), ['id'], unique=False)
        batch_op.create_index(batch_op.f('ix_partner_payments_vehicle_id'), ['vehicle_id'], unique=False)

    with op.batch_alter_table('vehicle_expenses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('paid_by', sa.String(), server_default='us', nullable=False))

    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('partner_name', sa.String(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('vehicles', schema=None) as batch_op:
        batch_op.drop_column('partner_name')

    with op.batch_alter_table('vehicle_expenses', schema=None) as batch_op:
        batch_op.drop_column('paid_by')

    with op.batch_alter_table('partner_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_partner_payments_vehicle_id'))
        batch_op.drop_index(batch_op.f('ix_partner_payments_id'))

    op.drop_table('partner_payments')
    # ### end Alembic commands ###
