"""add transport_total and transport_vat_amount to sales

Revision ID: 2e9581a672fd
Revises: 6d9ae1654218
Create Date: 2026-09-22 10:44:07.840441

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2e9581a672fd'
down_revision: Union[str, Sequence[str], None] = '6d9ae1654218'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport_vat_amount', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('transport_total', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('transport_total')
        batch_op.drop_column('transport_vat_amount')

    # ### end Alembic commands ###
