"""sale header + sale_items

Revision ID: 4f2c15ba8ea6
Revises: 119d08dcdede
Create Date: 2026-09-19 16:40:30.915510

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4f2c15ba8ea6'
down_revision: Union[str, Sequence[str], None] = '119d08dcdede'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('sale_items',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sale_id', sa.Integer(), nullable=False),
    sa.Column('product_name', sa.String(), nullable=False),
    sa.Column('quantity_kg', sa.Numeric(precision=10, scale=3), nullable=False),
    sa.Column('unit_price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('vat_rate', sa.Numeric(precision=5, scale=2), nullable=False),
    sa.Column('line_subtotal', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_total', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('line_vat', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.ForeignKeyConstraint(['sale_id'], ['sales.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sale_items_id'), ['id'], unique=False)

    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('note', sa.String(), nullable=True))
        batch_op.drop_column('unit_price')
        batch_op.drop_column('vat_rate')
        batch_op.drop_column('quantity_kg')
        batch_op.drop_column('product_name')

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('product_name', sa.VARCHAR(), nullable=False))
        batch_op.add_column(sa.Column('quantity_kg', sa.NUMERIC(precision=10, scale=3), nullable=False))
        batch_op.add_column(sa.Column('vat_rate', sa.NUMERIC(precision=5, scale=2), nullable=False))
        batch_op.add_column(sa.Column('unit_price', sa.NUMERIC(precision=12, scale=2), nullable=False))
        batch_op.drop_column('note')

    with op.batch_alter_table('sale_items', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sale_items_id'))

    op.drop_table('sale_items')
    # ### end Alembic commands ###
