"""add transport fields to sales

Revision ID: 6d9ae1654218
Revises: 68b487d4f039
Create Date: 2026-09-22 10:39:09.139023

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6d9ae1654218'
down_revision: Union[str, Sequence[str], None] = '68b487d4f039'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.add_column(sa.Column('transport', sa.Boolean(), server_default='0', nullable=True))
        batch_op.add_column(sa.Column('transport_price', sa.Numeric(precision=12, scale=2), nullable=True))
        batch_op.add_column(sa.Column('transport_vat_rate', sa.Numeric(precision=5, scale=2), server_default='20', nullable=False))
        batch_op.add_column(sa.Column('transport_tevkifat', sa.Numeric(precision=12, scale=2), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('sales', schema=None) as batch_op:
        batch_op.drop_column('transport_tevkifat')
        batch_op.drop_column('transport_vat_rate')
        batch_op.drop_column('transport_price')
        batch_op.drop_column('transport')

    # ### end Alembic commands ###
