"""add direction and payment type fields to payments

Revision ID: e8e8c55d2cb6
Revises: ecb3f9a24b9d
Create Date: 2026-09-23 20:47:46.390377

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e8e8c55d2cb6'
down_revision: Union[str, Sequence[str], None] = 'ecb3f9a24b9d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('direction', sa.String(), server_default='in', nullable=True))
        batch_op.add_column(sa.Column('payment_type', sa.String(), server_default='cash', nullable=True))
        batch_op.add_column(sa.Column('bank_name', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cheque_no', sa.String(), nullable=True))
        batch_op.add_column(sa.Column('cheque_due_date', sa.Date(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_column('cheque_due_date')
        batch_op.drop_column('cheque_no')
        batch_op.drop_column('bank_name')
        batch_op.drop_column('payment_type')
        batch_op.drop_column('direction')

    # ### end Alembic commands ###
